modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Wulian233/TextureLocaleRedirector/issues"
license = "MIT"

[[mods]]
modId = "texturelocaleredirector"
version = "${version}"
displayName = "Texture Locale Redirector"
displayURL = "https://github.com/Wulian233/TextureLocaleRedirector"
authors = "Wulian233"
description = '''
By extending the vanilla resource loading mechanism, it provides native multi-language texture support for resource packs, enabling localization of texture assets.'''
logoFile = "assets/texturelocaleredirector/icon.png"

[[mixins]]
config = "texturelocaleredirector.mixins.json"

[[dependencies.texturelocaleredirector]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.2,1.20.5)"
ordering = "NONE"
side = "BOTH"
