name: Build

on: [ pull_request, push, workflow_dispatch ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'build.gradle') }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-artifacts
          path: ${{ github.workspace }}/fabric/build/libs

      - name: Upload forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge-artifacts
          path: ${{ github.workspace }}/forge/build/libs

      - name: Upload neoforge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-artifacts
          path: ${{ github.workspace }}/neoforge/build/libs
